import type { Metadata } from "next";

import { PageHero } from "@/components/marketing/page-hero";

export const metadata: Metadata = {
  title: "Privacy Policy",
  alternates: { canonical: "/legal/privacy" },
};

const SECTIONS = [
  {
    title: "1. Information We Collect",
    body: "We collect information you provide directly (name, email, phone, address, vehicle details), information generated by using the service (booking history, location during active jobs, in-app messages), and, for mechanics, identity and compliance documents required for approval.",
  },
  {
    title: "2. How We Use Information",
    body: "We use your information to operate the marketplace: matching you with a mechanic, processing payments, providing live tracking, sending service notifications, and improving the platform.",
  },
  {
    title: "3. Location Data",
    body: "Customer address data is used to dispatch nearby mechanics. Mechanic location is shared with the customer only while a job is active, to power live tracking.",
  },
  {
    title: "4. Sharing of Information",
    body: "We share information with the mechanic or customer assigned to a job as necessary to complete it, with payment processors (Stripe) to process transactions, and with service providers (e.g., SMS and email delivery) strictly to operate the platform. We do not sell personal information.",
  },
  {
    title: "5. Data Retention",
    body: "Account and job data is retained while your account is active. Mechanic compliance documents (license, insurance, certifications) are retained only while an account is active or under review, subject to legally required minimum retention periods, and are deleted or anonymized after account closure or rejection.",
  },
  {
    title: "6. Your Rights",
    body: "You may request access to, correction of, or deletion of your personal information, subject to legal and operational retention requirements, by contacting privacy@revvy.com.",
  },
];

export default function PrivacyPage() {
  return (
    <>
      <PageHero eyebrow="Legal" title="Privacy Policy" align="left" />
      <section className="mx-auto max-w-3xl px-4 py-16 sm:px-6 lg:px-8">
        <div className="rounded-xl border border-warning/30 bg-warning/10 px-5 py-4 text-sm text-warning">
          Draft placeholder — pending final legal review before launch.
        </div>
        <p className="mt-8 text-sm text-text-faint">Last updated: July 7, 2026</p>
        <div className="mt-6 flex flex-col gap-8">
          {SECTIONS.map((s) => (
            <div key={s.title}>
              <h2 className="text-lg font-semibold text-text">{s.title}</h2>
              <p className="mt-2 leading-relaxed text-text-muted">{s.body}</p>
            </div>
          ))}
        </div>
      </section>
    </>
  );
}
